### ISSUE TITLE
Create a cloud-storage tool to check for non-contiguous fragments in a journal

### ISSUE THREAD

**Issue by pintohutch** [gazette/core#200]
When there's data-loss due to unclean Gazette shutdown, problems can ripple downstream (e.g. consumers could hit snags during recovery log playback). One can feel the result of this, sometimes hours or days later, without much warning. By indicating any missing fragments via an external process (e.g. a cli tool), we can be proactive in debugging and taking action on potential downstream effects.

**Comment by jgraettinger** [comment]
Hey @pintohutch 

I think this is a pretty easy tool to write (eg, against the ListFragmets() RPC), but doesn't belong in the gazette repo itself because it's not particularly actionable. There are plenty of valid reasons why ranges of journal would be removed: compliance, log pruning, etc. Further a tool like this wouldn't be able to distinguish between fragments removed due to regular recovery log pruning, vs fragments which were never persisted due to N>R broker failures. It's also not possible to determine a priori whether missing ranges of log impact a set of recoverylog hints without actually playing those hints.

If N>R broker failures occur, the operator simply has to get involved, eg by rolling back to earlier hints for shards which show themselves to be impacted, and that may only be determinable by attempting playback.

That said, in practice I believe this class of data-loss error on N>R broker / Etcd partitions has been greatly reduced due to recent changes.

**Comment by pintohutch** [comment]
Ok - that makes sense. Thanks for the reply! Closing.
