### ISSUE TITLE
Investigate TTLs in RocksDB

### ISSUE THREAD

**Issue by adayNU** [gazette/core#209]
RocksDB has an API which allows you to specify how long an SSTable can exist before it gets compacted. When compactions are run our compaction filter is applied and any rows which should be deleted because they are old will be deleted. 

However, it is the case that SSTable TTLs are not applied to SStables at the lowest level. This means that the oldest data, which is likely what is needed to be TTLed will not be. This task to investigate leveraging the existing rockdDB apis which tell us which SSTables exist at the lowest level and manually run compactions on the keyspace range encompassed by the SSTables.

cc @jskelcy

**Comment by jgraettinger** [comment]
I don't think this is actionable for gazette/core (though it is for LiveRamp/factable), as I'm also not aware of a way to convince RocksDB to go compact the lowest-level SSTs in order to drive compaction filter calls. It's a general open question with RocksDB AFAIK.

gorocksdb does expose the `CompactRange()` (iirc) API which can be used to force compaction of specific key ranges. Done periodically and with a good selection of key range (eg one likely to have a lot of data that can be thrown away via a compaction filter), that seems like the best bet. But it requires application domain knowledge over what key ranges are compacted, when, and why.

**Comment by jgraettinger** [comment]
Discovered that RocksDB recently added a "periodic compactions" TTL which applies to all levels of the LSM tree (including the bottom-most one, which the TTL setting we've played with before didn't apply to). This is potentially nice way to ensure a `CompactionFilter` is run regularly to chuck out old data (eg with [factable](https://github.com/LiveRamp/factable)). There's some cost from compacting / re-writing files you otherwise didn't need to touch though, so it undoubtedly needs tuning: https://github.com/facebook/rocksdb/pull/5166

**Comment by jgraettinger** [comment]
Closing as this isn't actionable for gazette/core itself.
